name: flutter_ai_toolkit_example
description: >-
  Sample apps showing off various features of the Flutter AI Toolkit.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: '>=3.27.0-0'

dependencies:
  flutter:
    sdk: flutter
  flutter_ai_toolkit:
    path: ..
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  go_router: ^14.2.8
  uuid: ^4.5.1
  path: ^1.9.0
  path_provider: ^2.1.4
  flutter_markdown_plus: ^1.0.3
  google_fonts: ^6.2.1
  future_builder_ex: ^5.0.0
  split_view: ^3.2.1
  firebase_core: ^3.13.0
  firebase_ai: ^2.0.0
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recipes_default.json
    - assets/halloween-bg.png
